Fix undeclared constants (previously included by png.h)
The undeclared constants are defined in zlib.h. Previously, png.h included
zlib.h, but recent versions of libpng (version >= 1.5) do not include zlib.h
anymore.

This commit will solve the following errors:

lib/io/_ccv_io_libpng.c: In function ‘_ccv_write_png_fd’:
lib/io/_ccv_io_libpng.c:55:23: error: ‘MAX_MEM_LEVEL’ undeclared (first use in
this function)
lib/io/_ccv_io_libpng.c:55:23: note: each undeclared identifier is reported
only once for each function it appears in
lib/io/_ccv_io_libpng.c:63:38: error: ‘Z_BEST_SPEED’ undeclared (first use in
this function)
lib/io/_ccv_io_libpng.c:65:40: error: ‘Z_HUFFMAN_ONLY’ undeclared (first use in
this function)