varies fixes for new build system via smvv
I cannot merge all @smvv's changes due the the fact that I cannot
understand all the dependencies of these makefiles, and the newly
changed tld.c file cannot pass my test video. Will do these merges
later, but for now, only limited changes are merged to mainline.

Fix C spec violation error due to missing -std=c99

Various build system and configure script improvements

Move configure script to root directory

Fix undeclared constants (previously included by png.h)

The undeclared constants are defined in zlib.h. Previously, png.h included
zlib.h, but recent versions of libpng (version >= 1.5) do not include zlib.h
anymore.

This commit will solve the following errors:

lib/io/_ccv_io_libpng.c: In function ‘_ccv_write_png_fd’:
lib/io/_ccv_io_libpng.c:55:23: error: ‘MAX_MEM_LEVEL’ undeclared (first use in
this function)
lib/io/_ccv_io_libpng.c:55:23: note: each undeclared identifier is reported
only once for each function it appears in
lib/io/_ccv_io_libpng.c:63:38: error: ‘Z_BEST_SPEED’ undeclared (first use in
this function)
lib/io/_ccv_io_libpng.c:65:40: error: ‘Z_HUFFMAN_ONLY’ undeclared (first use in
this function)

Rewrote build system for proper dependency tracking

This commit makes it also possible to build all binaries and the ccv library in
parallel using e.g. make -j4.

Add build/lib to ld's library search path

Cleanup and mark object files as precious (aka "do-not-remove")

Use conditional assignment for CC, CFLAGS and LDFLAGS

Integrate test/ in central build system (work in progress)

Fix C spec violation error due to missing -std=c99

Add test/ directory to header include path